[package]
name = "rarog-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-accessibility = { path = "../rarog-accessibility" }
rarog-compositor = { path = "../rarog-compositor" }
rarog-css = { path = "../rarog-css" }
rarog-dom = { path = "../rarog-dom" }
rarog-fetch = { path = "../rarog-fetch" }
rarog-html = { path = "../rarog-html" }
rarog-layout = { path = "../rarog-layout" }
rarog-paint = { path = "../rarog-paint" }
rarog-platform = { path = "../rarog-platform" }
rarog-resources = { path = "../rarog-resources" }
rarog-scroll = { path = "../rarog-scroll" }
rarog-scheduler = { path = "../rarog-scheduler" }
rarog-types = { path = "../rarog-types" }
rarog-url = { path = "../rarog-url" }

[dev-dependencies]
rarog-broker = { path = "../rarog-broker" }
rarog-canvas = { path = "../rarog-canvas" }
rarog-host = { path = "../rarog-host" }
rarog-ipc = { path = "../rarog-ipc" }
rarog-media = { path = "../rarog-media" }
rarog-platform-windows = { path = "../rarog-platform-windows" }
rarog-process = { path = "../rarog-process" }
rarog-storage = { path = "../rarog-storage" }
rarog-webgl = { path = "../rarog-webgl" }
rarog-websocket = { path = "../rarog-websocket" }
rarog-workers = { path = "../rarog-workers" }

[lints]
workspace = true
