[package]
name = "rarog-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-compositor = { path = "../rarog-compositor" }
rarog-css = { path = "../rarog-css" }
rarog-dom = { path = "../rarog-dom" }
rarog-html = { path = "../rarog-html" }
rarog-layout = { path = "../rarog-layout" }
rarog-paint = { path = "../rarog-paint" }
rarog-platform = { path = "../rarog-platform" }
rarog-resources = { path = "../rarog-resources" }
rarog-scroll = { path = "../rarog-scroll" }
rarog-scheduler = { path = "../rarog-scheduler" }
rarog-types = { path = "../rarog-types" }

[lints]
workspace = true
