[package]
name = "rarog-css"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cssparser = { version = "0.37", default-features = false }
rarog-dom = { path = "../rarog-dom" }
rarog-types = { path = "../rarog-types" }

[lints]
workspace = true
