[package]
name = "rarog-platform-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-platform = { path = "../rarog-platform" }

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-win = { version = "5.4.1", default-features = false, features = ["std"] }
font-kit = { version = "0.14.3", default-features = false, features = ["source"] }
rarog-compositor-wgpu = { path = "../rarog-compositor-wgpu" }
wgpu = { version = "=26.0.1", default-features = false, features = ["std", "dx12"] }

[dev-dependencies]
rarog-layout = { path = "../rarog-layout" }
rarog-text-opentype = { path = "../rarog-text-opentype" }

[lints]
workspace = true
