[package]
name = "rarog-platform-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-platform = { path = "../rarog-platform" }

[target.'cfg(target_os = "windows")'.dependencies]
font-kit = { version = "0.14.3", default-features = false, features = ["source"] }

[lints]
workspace = true
