[package]
name = "rarog-platform-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-host = { path = "../rarog-host" }
rarog-ipc = { path = "../rarog-ipc" }
rarog-platform = { path = "../rarog-platform" }
rarog-platform-windows-native = { path = "../rarog-platform-windows-native" }
rarog-process = { path = "../rarog-process" }

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-win = { version = "5.4.1", default-features = false, features = ["std"] }
interprocess = { version = "=2.4.3", default-features = false }
font-kit = { version = "0.14.3", default-features = false, features = ["source"] }
rarog-compositor = { path = "../rarog-compositor" }
rarog-compositor-wgpu = { path = "../rarog-compositor-wgpu" }
wgpu = { version = "=26.0.1", default-features = false, features = ["std", "dx12"] }

[dev-dependencies]
rarog-broker = { path = "../rarog-broker" }
rarog-fetch = { path = "../rarog-fetch" }
rarog-layout = { path = "../rarog-layout" }
rarog-text-opentype = { path = "../rarog-text-opentype" }
rarog-url = { path = "../rarog-url" }

[lints]
workspace = true
