[package]
name = "rarog-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rarog-dom = { path = "../rarog-dom" }
rarog-css = { path = "../rarog-css" }
rarog-types = { path = "../rarog-types" }
unicode-bidi = "0.3.18"
unicode-linebreak = "0.1.5"
unicode-script = "0.5.8"
unicode-segmentation = "1.13.3"

[lints]
workspace = true
